version: '3.8'

networks:
  db:

services:
  # api:
  #   container_name: nestjs_api
  #   build:
  #     context: .
  #     target: development
  #     dockerfile: ./Dockerfile
  #   command: npm run start:dev
  #   env_file:
  #     - .env
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped
  #   networks:
  #     - db
  #   depends_on:
  #     - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    networks:
      - db
